Exchanges:
  Ingestor:
    RecereateOnStartup: true
    ForceDelete: true
    Type: "direct"

Queues:
  Kline:
    RecereateOnStartup: true
    ForceDelete: true
    Features:
      DeadLetterExchange: "Ingestor"
      DeadLetterRoutingKey: "kline.dlq"
    Bindings:
      - ExchangeName: "Ingestor"
        RoutingKey: "kline"

  Kline.dlq:
    RecereateOnStartup: true
    ForceDelete: true
    Bindings:
      - ExchangeName: "Ingestor"
        RoutingKey: "kline.dlq"
