Exchanges:
  Ingestor:
    RecereateOnStartup: false
    ForceDelete: false
    Type: "direct"

Queues:
  Kline:
    RecereateOnStartup: false
    ForceDelete: false
    Features:
      DeadLetterExchange: "Ingestor"
      DeadLetterRoutingKey: "kline.dlq"
    Bindings:
      - ExchangeName: "Ingestor"
        RoutingKey: "kline"

  Kline.dlq:
    RecereateOnStartup: false
    ForceDelete: false
    Bindings:
      - ExchangeName: "Ingestor"
        RoutingKey: "kline.dlq"
