namespace CryptoBot.Application.LavinMQ.Contract.Configs;

public class ILavinMQConsumerConfig
{
    public required string QueueName { get; set; }
    public ushort PrefetchCount { get; set; } = 1;
    public bool AutoAck { get; set; } = true;
    public bool NoLocal { get; set; } = false;
    public bool AutoGeneratedInstanceOfService { get; set; }
}